{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.2-v1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.2-v1.toml",
          "url": "sharedcatalogs-1.20.2-v1.toml",
          "size": 2810,
          "sha512": "d02fa722ad672e6d9880bf85c46a92f0208730e7af6f9591ca96861430e44621968e1413f41aa6421c813d509f53cbb70edca622efff2aa4e0b265c6a2f56f60",
          "sha256": "f3a5cf7f176604541c11266296af2eaf9b332df13fddd32f73079ebc7057cacf",
          "sha1": "d891c8f6232c2473f3db234acdd41b9fea8abb8a",
          "md5": "8e74b1b6ad409fbbd23e1adfd46141b1"
        }
      ]
    }
  ]
}
