{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.23.jar",
          "url": "multiloader-convention-plugins-1.1.23.jar",
          "size": 1955148,
          "sha512": "d1499f0affdc521ab21e2e6fc864699a4a7ea8c7008700fd14579bdda419537ced3999606aa5077816e6f77c081b466c6f63287c704146d089ff10ac94baba17",
          "sha256": "f3dc40cf3198ac9bb9456e6893ae642d49ed69346251d4c16190104dd4267a6a",
          "sha1": "f34d1ea4bed73fd9dc57b19503cc6f87a3dcf421",
          "md5": "8dca05425a1478157d7324a622345d5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.23.jar",
          "url": "multiloader-convention-plugins-1.1.23.jar",
          "size": 1955148,
          "sha512": "d1499f0affdc521ab21e2e6fc864699a4a7ea8c7008700fd14579bdda419537ced3999606aa5077816e6f77c081b466c6f63287c704146d089ff10ac94baba17",
          "sha256": "f3dc40cf3198ac9bb9456e6893ae642d49ed69346251d4c16190104dd4267a6a",
          "sha1": "f34d1ea4bed73fd9dc57b19503cc6f87a3dcf421",
          "md5": "8dca05425a1478157d7324a622345d5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.23-sources.jar",
          "url": "multiloader-convention-plugins-1.1.23-sources.jar",
          "size": 868084,
          "sha512": "7453e0d40fb95153d97ac5dec93baf0d254246984f8d5735ace91dd6c7944451bb9bc4974fbbf7b50273ff1f2f2c639177e7b9dc3454114f9524c887ffee3cb9",
          "sha256": "6292fd95a207332cfd9893bfd1fc890faa218b090982572d122240831aad0a68",
          "sha1": "ee9a25369acbbbde324cf4bd1e63467920f811ef",
          "md5": "5fd1b8c2c7d72f53091f98f9617cb99a"
        }
      ]
    }
  ]
}
