{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.statuemenus",
    "module": "statuemenus-fabric",
    "version": "26.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "26.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "statuemenus-fabric-26.3.0.jar",
          "url": "statuemenus-fabric-26.3.0.jar",
          "size": 279152,
          "sha512": "c104507ccf0f91e02a96be544ffa7c7856561ab34095c470f91fb58b70c330cc5509242ad3690135c1582380755af4978536eb0602494aab3fcd3718675b0586",
          "sha256": "543aa2dec35ef69b9b67f8a7e36b782492ba91e744397eada051673499b7bdb5",
          "sha1": "a867d587d4e15ae16438313d46648e3de60b2929",
          "md5": "ad7abc36b418da1cf8eded5371915a06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.161.0+26.3"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "26.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "statuemenus-fabric-26.3.0.jar",
          "url": "statuemenus-fabric-26.3.0.jar",
          "size": 279152,
          "sha512": "c104507ccf0f91e02a96be544ffa7c7856561ab34095c470f91fb58b70c330cc5509242ad3690135c1582380755af4978536eb0602494aab3fcd3718675b0586",
          "sha256": "543aa2dec35ef69b9b67f8a7e36b782492ba91e744397eada051673499b7bdb5",
          "sha1": "a867d587d4e15ae16438313d46648e3de60b2929",
          "md5": "ad7abc36b418da1cf8eded5371915a06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "statuemenus-fabric-26.3.0-sources.jar",
          "url": "statuemenus-fabric-26.3.0-sources.jar",
          "size": 172793,
          "sha512": "fb6c9331f6a8f22175763dcc7d8a3965f02e89aa93f75daeec66631e759a251e4a5ee3dd96f66325a8b40ae69419d33296247220af1d28f383ec59a08f8073b1",
          "sha256": "2c1304388678db4d0aed2e48721a9857b245a69c536146e30afea00aa1626748",
          "sha1": "92dfe22f9d21660de52b9ce22ed0f78d5533bd06",
          "md5": "4b917f7fbf7bd60a0fb0e02db0a1fc25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "statuemenus-fabric-26.3.0-javadoc.jar",
          "url": "statuemenus-fabric-26.3.0-javadoc.jar",
          "size": 4503774,
          "sha512": "1b0b319ed178c5608bfde12bcc5c364e6bfcb11e7de394600dee8d6865e6020d3ec02a13248269894ce2f275c1044fdd517605080b23b17468dc99d429ece7b2",
          "sha256": "6a2e908a3fa7500660b4fb6378fe0b2880d5baa40f076604fecb52a6bc21b46d",
          "sha1": "6af29e6b06e8c964fec190cbd1f37fd5f96d2639",
          "md5": "cf7c423b58b353071398d034d5fa1496"
        }
      ]
    }
  ]
}
