{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.1-v22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v22.toml",
          "url": "sharedcatalogs-1.21.1-v22.toml",
          "size": 13676,
          "sha512": "1c08ee2c47250faab946988631ff96f08a190e30b86eaec64d6f7f865d037b2ac979960ba78db4b95b4da490604dbcec7437e0601c50b2443f0d55714eda535d",
          "sha256": "951b64d6cdb787535be61fa648c6b2377949d55de853c48ab34e6cd4af6d1c4e",
          "sha1": "8de35b8e012842ac5bfbc100b5c27e82dddb230f",
          "md5": "194bac50410533f82f09286f34a8f851"
        }
      ]
    }
  ]
}
