{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.4-v10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.4-v10.toml",
          "url": "sharedcatalogs-1.21.4-v10.toml",
          "size": 9388,
          "sha512": "b333d2ffdcb5246ecca6696765121ea5d376a6c3e606b37e9aeebe1e63362782660c6146cfe880193e7212b3d398e27198e2a77b9b671edb0dc501c35da7f2cd",
          "sha256": "4165513ba48ce242c6ecc719178ec9a96770326be9aa6acc143f791df28b3690",
          "sha1": "b0cffe324a5a5451afd0fb51b05fc47d9e4bb3a5",
          "md5": "3edd947ee413ae1144cd070cd75c847f"
        }
      ]
    }
  ]
}
