{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.puzzleslib",
    "module": "puzzleslib-common",
    "version": "21.1.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "21.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "puzzleslib-common-21.1.63.jar",
          "url": "puzzleslib-common-21.1.63.jar",
          "size": 1064660,
          "sha512": "7de77d260a065bdef3605afdfdf3d2912ab26848818fea6e57c18394378ffbe07c49822226c056b3e75b9c2157e4966d65599d1fa62b42e92b246bfbab221023",
          "sha256": "a50f243c96c7643232fe1cf8011d43ad005bee6f8ee335526859148ca8f3f915",
          "sha1": "14bf9d2a14176550d374155f17a566c0ec1e4ee9",
          "md5": "c9c00485482bf8a65c0c5363725129dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-common-21.1.63.jar",
          "url": "puzzleslib-common-21.1.63.jar",
          "size": 1064660,
          "sha512": "7de77d260a065bdef3605afdfdf3d2912ab26848818fea6e57c18394378ffbe07c49822226c056b3e75b9c2157e4966d65599d1fa62b42e92b246bfbab221023",
          "sha256": "a50f243c96c7643232fe1cf8011d43ad005bee6f8ee335526859148ca8f3f915",
          "sha1": "14bf9d2a14176550d374155f17a566c0ec1e4ee9",
          "md5": "c9c00485482bf8a65c0c5363725129dd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-common-21.1.63-sources.jar",
          "url": "puzzleslib-common-21.1.63-sources.jar",
          "size": 575022,
          "sha512": "b8acef555dfea82b91d2f4cf24be2a7748d3725bea21a08583b19a3c8f1a4037b36bc0c5cf72039c67887ab683e5f806ed7aa4c2b6da1663b5da218f31b54f58",
          "sha256": "db1488a3f8eafd2adce46f059feee7a6276e8c494b27ef888e257e1792bc23ea",
          "sha1": "645da9700c049d9cedbb32b77b9cd23b560a89e6",
          "md5": "cb337f2ed1147cdcb913595e0dbcb806"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-common-21.1.63-javadoc.jar",
          "url": "puzzleslib-common-21.1.63-javadoc.jar",
          "size": 3019087,
          "sha512": "373ce43d358ba03d506aeb0532150a7a5eb12161c02b36bd54c69ae8c5709bd5b6b7da85a91557d5e669c059b08b0146cdb902a32162fd868f57db3e68b12c5b",
          "sha256": "60d59778ffc5463505f5619d297d605ffab40a25af609d8af0169acb9c84ad87",
          "sha1": "069c10f052207a0d6ba57d98e65bafb3d53381b1",
          "md5": "511a2b39283fee328555c40a282388c2"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "puzzleslib-common-21.1.63-accesstransformer.cfg",
          "url": "puzzleslib-common-21.1.63-accesstransformer.cfg",
          "size": 78748,
          "sha512": "8048289d69dd2e0cc448763bc5914dd2417fb2e0454b9b76a2176ea700c75b8f5f5f819ad6fcb5a7f590e72ba6f5d21c2ee497f0af09a79785e3ec1b5bc80538",
          "sha256": "3d84beb1725c3c56ae1864d5c7014a58d6569918cf5b01f51b14674c1e54f980",
          "sha1": "97c03e7b817d15e269db8e73485acc428d79c544",
          "md5": "55cb111969ab10993bccd89e696ae9bb"
        }
      ]
    }
  ]
}
