{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs-plugins",
    "version": "3.0.0-v2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-plugins-3.0.0-v2.toml",
          "url": "sharedcatalogs-plugins-3.0.0-v2.toml",
          "size": 1134,
          "sha512": "3f676983766cd957e477d9efe59f93f686b510a6b002841300fd134c4968fcbdc11838ac3d5ead380fab31344619cd6301cc37009f7d4cb5055326ae781fa17c",
          "sha256": "c1bbb336434522c6ccdc9496c4b68318f560f30b6189671c747f6003a0924315",
          "sha1": "25491edb8fc9922ad5c367cb2d41d701cb3aaf17",
          "md5": "90bac3f25f227d194798d81c5098373f"
        }
      ]
    }
  ]
}
