{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.iteminteractions",
    "module": "iteminteractions-neoforge",
    "version": "26.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-neoforge",
          "version": {
            "requires": "26.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "iteminteractions-neoforge-26.1.3.jar",
          "url": "iteminteractions-neoforge-26.1.3.jar",
          "size": 188956,
          "sha512": "009323af8ee7c49093a2d780923b745d9f8f00b533a2b6b06b8ddf52d786093273230fc8a43c1f3ce0250dd46cadf81b8f5b2441240ec8b5744ffd93fbbac373",
          "sha256": "f83cd88d9102cb5241a647c332c6b3bfa751f3970991068d0cd5465177fdd504",
          "sha1": "843dcd5b258cc58a0b7b149fc31230873746d0ca",
          "md5": "c307dd8b0973bb77b86898602952f897"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-neoforge",
          "version": {
            "requires": "26.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "iteminteractions-neoforge-26.1.3.jar",
          "url": "iteminteractions-neoforge-26.1.3.jar",
          "size": 188956,
          "sha512": "009323af8ee7c49093a2d780923b745d9f8f00b533a2b6b06b8ddf52d786093273230fc8a43c1f3ce0250dd46cadf81b8f5b2441240ec8b5744ffd93fbbac373",
          "sha256": "f83cd88d9102cb5241a647c332c6b3bfa751f3970991068d0cd5465177fdd504",
          "sha1": "843dcd5b258cc58a0b7b149fc31230873746d0ca",
          "md5": "c307dd8b0973bb77b86898602952f897"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iteminteractions-neoforge-26.1.3-sources.jar",
          "url": "iteminteractions-neoforge-26.1.3-sources.jar",
          "size": 100224,
          "sha512": "99b56b453e3f3488fff445ffcb3b784f56f721afcc52306801f6a79fc382e1bb867d7dbf143018e0606e801235c8fda09179ed095967c8c5a1b46d0a4c79b013",
          "sha256": "993f414d7d3a029f154d4a0e18d6f897f668aa7245c71d49248ab57b81c69c57",
          "sha1": "ce2f186f9e1c13bc0bd9d29e8bdb6f071fd094ac",
          "md5": "6185b1c054c001f15b295426f7ef5e41"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iteminteractions-neoforge-26.1.3-javadoc.jar",
          "url": "iteminteractions-neoforge-26.1.3-javadoc.jar",
          "size": 4489161,
          "sha512": "10b5e286198b54a8ead04765e193193ddb0df83fa96fd3bbde2d028366762acb14515a5f37dfaad569ac76ffee9e84962942e8b81f5b1d69866f5366185f03c9",
          "sha256": "003016f9a8efe944f2e8969b4816a2e641d9a2f6f7d79ebfffb1ce84515d6b32",
          "sha1": "c4ee37e5b0e4dcb771d7f0ec554b84ff811a4a99",
          "md5": "d4e1d6164f3c69b85956346eaa195824"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "iteminteractions-neoforge-26.1.3-accesstransformer.cfg",
          "url": "iteminteractions-neoforge-26.1.3-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
