{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.18.2-v8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.18.2-v8.toml",
          "url": "sharedcatalogs-1.18.2-v8.toml",
          "size": 5971,
          "sha512": "7290443c912bd0909087d63f5ef37e4050c4abe57aed837469e63596cd8570aa164b7838d64edc24aa0be94b6a805474e6b3419690b707a2f4e4527465ef08cc",
          "sha256": "cee3b18d6bc6b43b871703adc67477b55af36983b49d5a131bc273e6fb977c5c",
          "sha1": "07214d19d84fefd84d3c4d797033a3022e938ea1",
          "md5": "78dc08207f406620f2c3a30fc286b2d1"
        }
      ]
    }
  ]
}
