{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.11-v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.11-v4.toml",
          "url": "sharedcatalogs-1.21.11-v4.toml",
          "size": 8694,
          "sha512": "41c3df2ab5b8ba92871c5deac41b079fbb9c1e1c5b9f538792ddce0b3efa075d056de2a3d322f1e0ed06a6178c13a7be24319256881ba810e278a80164b65f91",
          "sha256": "bad80b5ff1a10befe32c6843ce298a43d06c8851726b88fc01cf3b843caec40d",
          "sha1": "c12a3f56438be4ab85961e79fa0ab60ccc33566f",
          "md5": "ad052088b9498afad31871f51d2b2a2b"
        }
      ]
    }
  ]
}
