{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.5.jar",
          "url": "multiloader-convention-plugins-1.1.5.jar",
          "size": 1492109,
          "sha512": "3a9d511eacac237da4aa3e202ef6277223e1bc559122257f99a204a07b361183899e7556a60a205cec37c696f788cbfb56136908c7021ac1eece013065ee5d3d",
          "sha256": "6ee3d3fd911394d9c3f38fc5ab814b1f3af93e0b71d56b8e2346b6d490ae83b8",
          "sha1": "02df26090ed9a9934f5879897a6b4eaf8a4deebf",
          "md5": "5dc3e49e89b3ccd74b9f7d8df2b9edd8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.5.jar",
          "url": "multiloader-convention-plugins-1.1.5.jar",
          "size": 1492109,
          "sha512": "3a9d511eacac237da4aa3e202ef6277223e1bc559122257f99a204a07b361183899e7556a60a205cec37c696f788cbfb56136908c7021ac1eece013065ee5d3d",
          "sha256": "6ee3d3fd911394d9c3f38fc5ab814b1f3af93e0b71d56b8e2346b6d490ae83b8",
          "sha1": "02df26090ed9a9934f5879897a6b4eaf8a4deebf",
          "md5": "5dc3e49e89b3ccd74b9f7d8df2b9edd8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.5-sources.jar",
          "url": "multiloader-convention-plugins-1.1.5-sources.jar",
          "size": 589758,
          "sha512": "e73f1e2118ebbbb2f52c9c7fd36f2b801127fc0065e006ca1d3c992051156b797d3aa8996288454d6ff234a881f97dae0fc7618cd0b44731843cf43d599ea3b8",
          "sha256": "07190cdada669e0b0d1e211d4629be7d7207ffed0052a9be42d53b140c6498e8",
          "sha1": "7792a0afc93ca198377e2fe53cb9aec7ea153b9e",
          "md5": "d1f419844da66b87ecd038dd2b9d1dcb"
        }
      ]
    }
  ]
}
