{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.10-SNAPSHOT.toml",
          "url": "sharedcatalogs-1.21.10-SNAPSHOT.toml",
          "size": 11006,
          "sha512": "101b357876e1f74ed8cfcb64207bebd9ebbbdf66f1866c5ae9db187fb093c8e483a933c1621277bdddbd8e26cade19c9acff536f2c13d11230eb145cb542b13e",
          "sha256": "1cc73279e4987d7c4767208c5724c49e630e0c32edcd9d5306fcbca8eecf0ccb",
          "sha1": "761918a02745dbd1964899cf3c824c67b0af3440",
          "md5": "5b77eb7983b8e4e1d9e5a33e136751a9"
        }
      ]
    }
  ]
}
