{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.6-v8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.6-v8.toml",
          "url": "sharedcatalogs-1.21.6-v8.toml",
          "size": 7460,
          "sha512": "a6b451b29ffcd9f9ee2e20adfb6734ff9a7aceab12db9773bc12bfb5a6e9dc1e006c904970c4b8916854ce719e5e9c59cfff892a3f01b0fd4a704660996817a2",
          "sha256": "e363eddb1df774741c8659b7d9a074d7fbbfc159fdf696a234fa427e656f332a",
          "sha1": "3aa4eeabf0dfdcffb938d7d7ef60e9652b2712ef",
          "md5": "5253623a1b75428aab1c45739cfa3fcb"
        }
      ]
    }
  ]
}
