{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.1-v22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v22.toml",
          "url": "sharedcatalogs-1.20.1-v22.toml",
          "size": 8075,
          "sha512": "819d0ec148abd473713046a13546bde5a823a01d3f6202301a538959b748f90942b8c486e36aa19e81016fd23ba1a6e0f9da28e93880c29476b29b0d76b81939",
          "sha256": "6c399ec9a4a62eeaff2b0d88932650f055f359c62583081d75afc3667f060d7e",
          "sha1": "1226b567fe11abcbe0989efa1a2d1695857373e3",
          "md5": "aac3bcb09e4753dab280f9d5a5db2f82"
        }
      ]
    }
  ]
}
