{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.1-v13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v13.toml",
          "url": "sharedcatalogs-1.21.1-v13.toml",
          "size": 11260,
          "sha512": "e3e2a99116f9df4fa07fb7a7c773d54385780d7a630e88e64601a9fac8349bebe3238b8382e8072e070b641461c65c34c69c4d4b865484ab0f021bfb5a2178e6",
          "sha256": "4687eaa1c77c20f6f7b66a8254200e9f9a46411ca46cc4d4d099472a2166bdd7",
          "sha1": "734059da2cbce88da9a0b42af19271bde30275f4",
          "md5": "865b55ce15acda9f4c5924f4143589f0"
        }
      ]
    }
  ]
}
