{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.4-v9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.4-v9.toml",
          "url": "sharedcatalogs-1.20.4-v9.toml",
          "size": 4830,
          "sha512": "f4721c757eb9a09a1b1575173bb86cdca2ee9bcb9b2a62a08cd0226964cc74ed1ef84f96fb70401cf6a2d02df60b77c916b57c7bfbd81681a3ddf2fab59bc085",
          "sha256": "5605ddc59a8fdd17196b27ff804a052d23fb489f75417afe0115bac853b29228",
          "sha1": "677744a34b0649192197a7f17de56873993ee4f7",
          "md5": "b06f0ff0a425f29daca88fdc58da43d1"
        }
      ]
    }
  ]
}
