{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.4-v19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.4-v19.toml",
          "url": "sharedcatalogs-1.20.4-v19.toml",
          "size": 10049,
          "sha512": "6a966c243c6cc0b43e3ce90714f13c5d029d83c57571a2f793dc75e763140703e443061776d81ca6d10b90214555ef405614e32d2c02435e78a2942c0017c3e6",
          "sha256": "e091f4dad4a9984dda65239d86dc56b547b6299cb7168a49dcbb357b193fc7ed",
          "sha1": "e483a16ae1f02233e18a6b5215c608dc5db52092",
          "md5": "5d715cecc5c7361eb2416d5fff9398a5"
        }
      ]
    }
  ]
}
