{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.37.jar",
          "url": "multiloader-convention-plugins-1.1.37.jar",
          "size": 2424091,
          "sha512": "1a33e186668d40571d77213f6cb6a379c7058ae431a71413367cb00f880921213ac27360982397851f7636318924036c179513c92d2fadac5c2f1c5df2d40c34",
          "sha256": "4c373029fae974719ecc9e1167980999912a21c29b5ef8e551a29b0bedd8b3cb",
          "sha1": "d48e5656f0d6f88c568b687699f17c589dcb58ae",
          "md5": "ede6bd8fbd5ac59df5e5afc53cd315f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.147"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.37.jar",
          "url": "multiloader-convention-plugins-1.1.37.jar",
          "size": 2424091,
          "sha512": "1a33e186668d40571d77213f6cb6a379c7058ae431a71413367cb00f880921213ac27360982397851f7636318924036c179513c92d2fadac5c2f1c5df2d40c34",
          "sha256": "4c373029fae974719ecc9e1167980999912a21c29b5ef8e551a29b0bedd8b3cb",
          "sha1": "d48e5656f0d6f88c568b687699f17c589dcb58ae",
          "md5": "ede6bd8fbd5ac59df5e5afc53cd315f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.37-sources.jar",
          "url": "multiloader-convention-plugins-1.1.37-sources.jar",
          "size": 1175652,
          "sha512": "418b8ca06e1c95d53fb04db9ff3978e8744ba6fe94281d208dbdd861cadc9b7f7a798b4757dc2db3326464dd27ada35085a661f4b5508a09fa012f6ea1bbf971",
          "sha256": "e74295efb28a9df97df69b2ea62ad64bee15ce797e292d9c42fd27dbfdfdeb6c",
          "sha1": "d08c5a6590b6981845c6626bbbe056e4655408c8",
          "md5": "6f147c6eac1a0f0b072d6e289b10fa81"
        }
      ]
    }
  ]
}
