{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.1-v17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v17.toml",
          "url": "sharedcatalogs-1.21.1-v17.toml",
          "size": 12009,
          "sha512": "0cd8ae04699e3444bb8ee446e4a076ae6715bf54a1e0d93b6b583cbc01283b1b9b8aaef65ac4d5fa206a4c477b822356583713a44b313048ba9019cb2cb6fdb5",
          "sha256": "2e142a5dc5ccceaa560aa134a347fd9fbedb4b7af37c96792154b2c2b26419f4",
          "sha1": "d881f5541f686685d30a25dc34d7215ca6e48535",
          "md5": "ee79bc6dfe6f5e9e798d2cc808a41c35"
        }
      ]
    }
  ]
}
