{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.4-v11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.4-v11.toml",
          "url": "sharedcatalogs-1.21.4-v11.toml",
          "size": 9388,
          "sha512": "7c8a597d5931548a6fcaeabc7178d661b7f144e075047aeec29023abde0aae327fe5027ebd0dab7717193de15da3af8976c8f620b2d918f49e98c10fd186b21a",
          "sha256": "54e071a76bcac1069c63c29bc8a702b7637cacd0e47d76f98ec3ced9e84a26d8",
          "sha1": "4f236548d50871078b83f050405d4c4867242e01",
          "md5": "ff25594e84e47d3c0752b5a24abc58b5"
        }
      ]
    }
  ]
}
