{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v20.toml",
          "url": "sharedcatalogs-1.21-v20.toml",
          "size": 9581,
          "sha512": "a58e371fbbf4870b1fd85b1aae74ee35e852cf8f018f8367d60273e42d5ea495cff8bb112bba985e05b3835f333ec1f40cd40283ad85ec0634384565ca3c359f",
          "sha256": "3defcfab38f5e3d3bf942bd221404ffa1fd46002cf9b348b0dcc2e3c4fa54747",
          "sha1": "dc43c43b4e72fa4b7644a9c28d8a00785ee7d8e1",
          "md5": "5d8caecb785072af91d73487f5436057"
        }
      ]
    }
  ]
}
