{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.puzzleslib",
    "module": "puzzleslib-neoforge",
    "version": "26.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.9.jar",
          "url": "puzzleslib-neoforge-26.1.9.jar",
          "size": 1059169,
          "sha512": "b1f000a97ec0bfec75433733cf05978a95428d9ac03c21374a67e96b6d960a9326a18da98215fdf07ef62495fa8b5c048e6c1cd080bab34cea26604f2d8d0c52",
          "sha256": "f7a1f04ef47182f8e8e82a901df2d565817869836537cf5e2e60cc571493bcfb",
          "sha1": "1eeba88d626ca258b805ab12408d0b207fd1dade",
          "md5": "b582305ac0cb3bdd81929308c97d0741"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.9.jar",
          "url": "puzzleslib-neoforge-26.1.9.jar",
          "size": 1059169,
          "sha512": "b1f000a97ec0bfec75433733cf05978a95428d9ac03c21374a67e96b6d960a9326a18da98215fdf07ef62495fa8b5c048e6c1cd080bab34cea26604f2d8d0c52",
          "sha256": "f7a1f04ef47182f8e8e82a901df2d565817869836537cf5e2e60cc571493bcfb",
          "sha1": "1eeba88d626ca258b805ab12408d0b207fd1dade",
          "md5": "b582305ac0cb3bdd81929308c97d0741"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.9-sources.jar",
          "url": "puzzleslib-neoforge-26.1.9-sources.jar",
          "size": 533953,
          "sha512": "37d3982a92f12f7b2e7d3e961068570101e139522485439424ea7025fc2b8580796e4f807457fc016d79914557bf44a0fd14bec989f3a7f686970b7cfee92f3c",
          "sha256": "0ddd06c07978d8bd80ea71cba7d0300537cd69267da5261657652d0229226d85",
          "sha1": "6196f0fc538046f3f19813ba277b3d877ee5f316",
          "md5": "4472a7ad8842531b054eec58ed2f4368"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.9-javadoc.jar",
          "url": "puzzleslib-neoforge-26.1.9-javadoc.jar",
          "size": 6913180,
          "sha512": "1b9ef4c9d1165e5ae896f34331fd08cc0452e0dbff15dd99812364426ba2934dd17269d3d55ec65130ba2262fe8ebfed90b686b0bda7960c77e2f04d62c55490",
          "sha256": "75f63617e2aeed3fcbe95bcfb81868c180b8f9ebb464b92518fec0126cd3bb42",
          "sha1": "02af72b49c2a2e9e0c7b7869521e12a26fb07367",
          "md5": "1fd1099e9b0e08f74b879460b3a7b84c"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.9-accesstransformer.cfg",
          "url": "puzzleslib-neoforge-26.1.9-accesstransformer.cfg",
          "size": 99824,
          "sha512": "59fcaf2750d6d04a51d4e1dff9d9a4adcc6de44fa6609bdf9e138773c0db58aab0c9862fa2e2f0b94d1f605d3eb7a730d2439237c7faeb8a72af7c88a0ec4364",
          "sha256": "ddfa98260aa6320df732072ffdaa1774df671c4428f7c85bc6d7ca8251b188fa",
          "sha1": "3e324829b59d252ebe7c3d3879639003bb52e446",
          "md5": "99f3080d1075ffc62fb905a633b0d174"
        }
      ]
    }
  ]
}
