{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.6-SNAPSHOT.toml",
          "url": "sharedcatalogs-1.20.6-SNAPSHOT.toml",
          "size": 6185,
          "sha512": "15d848a47d89bce78c6e63a750e25f1194fe8194e3115cdaba56a288cbb55e97f72cf018f0736e18c38773d0729897554f522904e538dcfc4dbbc3f11880b936",
          "sha256": "1200e77b946472112696ae37b3973d7c13eccf1dfd8989853e4ebec5a224e0bc",
          "sha1": "ee591cb8ee04df2e605facbf44f13e56624b8a5b",
          "md5": "018374d42e28a3d3630423ae2ef8377d"
        }
      ]
    }
  ]
}
