{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.18.2-v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.18.2-v5.toml",
          "url": "sharedcatalogs-1.18.2-v5.toml",
          "size": 5736,
          "sha512": "a78e0f46f57f9ab3fdbf9559702c8e39e0b62245614e5045902f146d58dc5184af2fc3822a0bb878c617e46211e9cdb3811e77e1769ac9a229b28c634083f5b0",
          "sha256": "0a8f5ba2906f11641df79ecceb84a988b6dc0a41122988135a0caf1add419326",
          "sha1": "d46090ec227e06eaa8981bb73edbd51857842c04",
          "md5": "b94f4599ebcacd959c79912a2c237ef8"
        }
      ]
    }
  ]
}
