{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v12.toml",
          "url": "sharedcatalogs-1.21-v12.toml",
          "size": 9044,
          "sha512": "355054563abbbcd44276cfda8503101d2cd3a8f4f9722a33464a4229001be770eb2f2f400ce02f17715371cd782b4f7687e7f69af013e376cb3376e9c3d037d0",
          "sha256": "24584657424f3b36b8361cdd2d1bedf65a2c4dfcf9883f3beab05c09591970de",
          "sha1": "546addc0e9de04c0fb7a306dcb32f49a7fa8cade",
          "md5": "b5163eab36575278be274988344141d6"
        }
      ]
    }
  ]
}
