{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.30.jar",
          "url": "multiloader-convention-plugins-1.1.30.jar",
          "size": 1974951,
          "sha512": "998e494df0c0648a7c570615ac8c5a01ee68bb34c2e60c78df94f72f834a381265f8c02367961a255ab9c85ebfcaa0b3f8ab24d77bfdc811ead04e48d3d6d289",
          "sha256": "4f46099fd09663091dbb5ebd42f69de5e72c2e9c498dd06a9f717623f2ee76d8",
          "sha1": "c76287035f5ad05e09fe500f16a53e2a91ef5a2c",
          "md5": "15ce238f371252668cb63d55692408b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.30.jar",
          "url": "multiloader-convention-plugins-1.1.30.jar",
          "size": 1974951,
          "sha512": "998e494df0c0648a7c570615ac8c5a01ee68bb34c2e60c78df94f72f834a381265f8c02367961a255ab9c85ebfcaa0b3f8ab24d77bfdc811ead04e48d3d6d289",
          "sha256": "4f46099fd09663091dbb5ebd42f69de5e72c2e9c498dd06a9f717623f2ee76d8",
          "sha1": "c76287035f5ad05e09fe500f16a53e2a91ef5a2c",
          "md5": "15ce238f371252668cb63d55692408b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.30-sources.jar",
          "url": "multiloader-convention-plugins-1.1.30-sources.jar",
          "size": 870998,
          "sha512": "ef555ea3d2e476199c8e8427254b5d9c689f32c5348da5cd06caa13734da2b4d9869f44cf4e082e47202579dfad5d70097b9c3480f711f92b94089d64f3c20a1",
          "sha256": "c6bbf41ec0d8abb90dd5781eee1b91f9bb54bf7010efb822c0e82e1115b97493",
          "sha1": "708872953e34fffd7cbc8c71103730c2af3d7b63",
          "md5": "50b5f64587030ea0b56cfe9b6f03a950"
        }
      ]
    }
  ]
}
