{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.1-v8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v8.toml",
          "url": "sharedcatalogs-1.21.1-v8.toml",
          "size": 10734,
          "sha512": "082be860bc9385e1af11a77ad0539377d31c05bebd3251a04e069897478f980f728d7d5f4620ee98d2221db44d71fbfdd375928de584522944eb33985aeb4f26",
          "sha256": "2f62d35b7f12d0e579c7bfd0df6a5d4c3f520c2c6d9fd8e7e5bf92afd67c19cf",
          "sha1": "f25d601d4eaefb3680789ca854da90dca3012dec",
          "md5": "0f20298de1d70073174bd8100d9b3da5"
        }
      ]
    }
  ]
}
