{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.6-v1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.6-v1.toml",
          "url": "sharedcatalogs-1.21.6-v1.toml",
          "size": 2880,
          "sha512": "09138a31e21c23ccbd9f932b4f773c166dc82496d199c038247065850631eb6c68bb492a27ebbaaeb69271544df97ce42a1a8276bc610bbfafaf622f86affe9b",
          "sha256": "d960201773e340a2aa7f2a202fdd6d3f8fb36b99e40b196b5cfaa53ea7eb8807",
          "sha1": "21d08ff1820ad899d1461c414c4715d4194543db",
          "md5": "4ae399185f63518c7779fad9f9c05623"
        }
      ]
    }
  ]
}
