{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v15.toml",
          "url": "sharedcatalogs-1.21-v15.toml",
          "size": 9043,
          "sha512": "9447a2c4ba90931c006978af8dd02f43c553819babbc3d43696f9d1b716787d8377f11088a9581e14577888a05fffb5567966575f012eb0e5b19f910142ff3d9",
          "sha256": "f2fc359b4755d4d6b82dc18662af45ad62d7a2fcb5a507373a8f7fd1469845d5",
          "sha1": "bfe9b18030249a094c2b5616a8a8912047be8ffd",
          "md5": "9232bf85d6f088062553d4d12fb5c45e"
        }
      ]
    }
  ]
}
