{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs-libraries",
    "version": "1.21.1-v20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-libraries-1.21.1-v20.toml",
          "url": "sharedcatalogs-libraries-1.21.1-v20.toml",
          "size": 12929,
          "sha512": "7a107f9a8216ab3ce1c79af638949bbf8c8af1dcf04ce943a77b9a1a383da7e82b1b231c1ae4bf172615c7c1b7517fbcbaa95367fc8966a96ccb453494cdaa1b",
          "sha256": "db3faa76bd61eea08a14937f3f48a7b42cc6204f7bc1e46c4860ae69c2c2208f",
          "sha1": "029098567b96411d6cc461818d9c982b44ffccae",
          "md5": "71e18e6a3ef486bba1f1b9546bbea252"
        }
      ]
    }
  ]
}
