{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.1-v20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v20.toml",
          "url": "sharedcatalogs-1.20.1-v20.toml",
          "size": 7317,
          "sha512": "e70de1e4249d134b2d1f0d830d984ffe9b197d4d6531b36222f756d2dc6a4b333d32176db4c65f3b3e13d8469475100d576f1f42786de68f57911d85e19d2567",
          "sha256": "26ee7873fc4798df4451078b2295bb134cca041b3dbb6c1b1be4aebb81d15f78",
          "sha1": "c230f86066df66845ccd415c02a4fc7905125ced",
          "md5": "b08d2adfeeadfcaecd9b97c337b7b411"
        }
      ]
    }
  ]
}
