{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.33.jar",
          "url": "multiloader-convention-plugins-1.1.33.jar",
          "size": 2419328,
          "sha512": "7501b4f474533b841cf3258eb5fa5bcb68b3042ce67f6833ee222b4b6d4d70001af8e836937d960d35b34f1f23f90fd0f60ae80ee07229057766843f3f6a4d40",
          "sha256": "fe20ed72d048debbf1f8ec92fb2d0372f4dbdc9943d8bc32669ee57dacb13d6f",
          "sha1": "d3d706fa0b84033560a2b92162b2c4a55c43ad50",
          "md5": "9fce8c39323ea256624a07831a0cd9a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.+"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.33.jar",
          "url": "multiloader-convention-plugins-1.1.33.jar",
          "size": 2419328,
          "sha512": "7501b4f474533b841cf3258eb5fa5bcb68b3042ce67f6833ee222b4b6d4d70001af8e836937d960d35b34f1f23f90fd0f60ae80ee07229057766843f3f6a4d40",
          "sha256": "fe20ed72d048debbf1f8ec92fb2d0372f4dbdc9943d8bc32669ee57dacb13d6f",
          "sha1": "d3d706fa0b84033560a2b92162b2c4a55c43ad50",
          "md5": "9fce8c39323ea256624a07831a0cd9a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.33-sources.jar",
          "url": "multiloader-convention-plugins-1.1.33-sources.jar",
          "size": 1175433,
          "sha512": "80ebb75d964ed21d7856db68769f37c0616e6fc5dad9ead0c7266797ad7c1d8156ce1cdcd95d475a7378170067c8eb99e804c05b7977890197cd3677a906366e",
          "sha256": "e360c7cb919e919f3e68b963cffe496930866c61ac813096a4018a635a582815",
          "sha1": "2decaf6de33a23ee196d282b27ddffec04ecf6de",
          "md5": "e1f6636cdfa764b5cc47740d7fbf3736"
        }
      ]
    }
  ]
}
