{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.4-v21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.4-v21.toml",
          "url": "sharedcatalogs-1.20.4-v21.toml",
          "size": 10668,
          "sha512": "a4bce36c97f598a8295defbd8c767e43c4d9f1c8f1984963feb63ecd62fbdf94cb733a42136972db448b9aedda0de63c05b5116dd6df7aa87efd6cc98a5fdd62",
          "sha256": "f64c1a0768bc2ca6b1af40a229c60afdb2478315e64885ac279a2c0ef3a8bdbe",
          "sha1": "8241e38f7a6b131d1aea030f8e2f08fa896ee04f",
          "md5": "33393bd1e6a8632fcea940a9b5c7ddf5"
        }
      ]
    }
  ]
}
