{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.19.2-v9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.19.2-v9.toml",
          "url": "sharedcatalogs-1.19.2-v9.toml",
          "size": 5971,
          "sha512": "d8b062fcc22cef10fe776497b8a250961d43ceeadb177643d08aa3e030299a3b375ceeed6c28a977d4803c5e17053dae519cab0e1662e5de50cabf5bf3d96baf",
          "sha256": "c5724225d892e8390beeee6763122d8ae91f1dfe4b4d7fb47d9f498d790e86e0",
          "sha1": "89c6015183af6465d1d4f269c0e14139f58fc36a",
          "md5": "73ac8556d98d6e96a8cf63a9c3da0dde"
        }
      ]
    }
  ]
}
