{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20-SNAPSHOT.toml",
          "url": "sharedcatalogs-1.20-SNAPSHOT.toml",
          "size": 5747,
          "sha512": "78a0232b41e591a82aebc3f3bfe8646298f5c4c6189f2089ca8a90ab3aedc92ac4164798b55e37d61ef9815d12b2976d3392148a232604d3697adf1aae389abb",
          "sha256": "1a87df05fd5b96619b63cdf79c93a13796052608f188ead24c8b56832945fc8c",
          "sha1": "f910c95c56337214258d4d104f67b15ec03a0b9e",
          "md5": "10e0c8732a3d921a8d00496f30755100"
        }
      ]
    }
  ]
}
