{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.4-v12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.4-v12.toml",
          "url": "sharedcatalogs-1.21.4-v12.toml",
          "size": 9388,
          "sha512": "e1cc878d525026b69bd52201fc89a4817d4c30114498a6e344214ef2b941fa38fa61b48041ab4b4f00441998ec18c699f2baa74bf2853605e4fbef27a7ad2400",
          "sha256": "9ee88b8b0aa94f9446474b12d89498738c215245609955edb759157b1dd7d21b",
          "sha1": "81f51e6b260c3b2d8443387c8fad89d0cb1fdfb1",
          "md5": "052e67019e98899df97760a868c73cab"
        }
      ]
    }
  ]
}
