{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.puzzleslib",
    "module": "puzzleslib-common",
    "version": "26.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-common-neoforgeapi",
          "version": {
            "requires": "26.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "puzzleslib-common-26.1.11.jar",
          "url": "puzzleslib-common-26.1.11.jar",
          "size": 789628,
          "sha512": "6dce0990989422d69ce01ffe1b6e282e8bf6afeee6e58df7a640c018562e1e51a151a7110b38e9fe2c3707d1316833687809ce47187027aa4ecb57d7f0b7d390",
          "sha256": "c008fc68c191d55da8d094a70bbe49628c6146fa0ee39558c33a963e0cc28d21",
          "sha1": "be34ca220243bd334b0a4073e365ba1c0323865b",
          "md5": "544ced03334f5722b4a5e0dded3416bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-common-26.1.11.jar",
          "url": "puzzleslib-common-26.1.11.jar",
          "size": 789628,
          "sha512": "6dce0990989422d69ce01ffe1b6e282e8bf6afeee6e58df7a640c018562e1e51a151a7110b38e9fe2c3707d1316833687809ce47187027aa4ecb57d7f0b7d390",
          "sha256": "c008fc68c191d55da8d094a70bbe49628c6146fa0ee39558c33a963e0cc28d21",
          "sha1": "be34ca220243bd334b0a4073e365ba1c0323865b",
          "md5": "544ced03334f5722b4a5e0dded3416bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-common-26.1.11-sources.jar",
          "url": "puzzleslib-common-26.1.11-sources.jar",
          "size": 427143,
          "sha512": "3b8d14582df359bd4b8bc42bd7ecd916fccab79bf8fb68dca35c72962094c324216274f3873c364bfa4c6e1f58de8fce2f2845d576b50616dfecd5ca216dbcbd",
          "sha256": "36aecf63d9d460750b355b06e039384a759eaa00ce25cc9ac3d8fa0bf7a8d308",
          "sha1": "e1f318710eca63e98b90ba30e7bbaa7cc42b6aef",
          "md5": "4c28d2903c6882e995ee33a818efaf6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-common-26.1.11-javadoc.jar",
          "url": "puzzleslib-common-26.1.11-javadoc.jar",
          "size": 6411790,
          "sha512": "af201144fa398f42c139f5f5471f6d2d7bacc18170eb19bedd0c41c4a6934c796d9ea011e8e9b8a2707694975130c734793a5bf0c82dc59eed17390495730bec",
          "sha256": "47aae9cacf9ab00b962e590a0e4ec7d02c06f4933d61d9e5897771890cc1704a",
          "sha1": "45df5a1f933be7af8ed1c0251811e726bef80c4b",
          "md5": "4e6e0128b1b710a4cf445ffe5ff5b733"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "puzzleslib-common-26.1.11-accesstransformer.cfg",
          "url": "puzzleslib-common-26.1.11-accesstransformer.cfg",
          "size": 99824,
          "sha512": "59fcaf2750d6d04a51d4e1dff9d9a4adcc6de44fa6609bdf9e138773c0db58aab0c9862fa2e2f0b94d1f605d3eb7a730d2439237c7faeb8a72af7c88a0ec4364",
          "sha256": "ddfa98260aa6320df732072ffdaa1774df671c4428f7c85bc6d7ca8251b188fa",
          "sha1": "3e324829b59d252ebe7c3d3879639003bb52e446",
          "md5": "99f3080d1075ffc62fb905a633b0d174"
        }
      ]
    }
  ]
}
