{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.1-v25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v25.toml",
          "url": "sharedcatalogs-1.20.1-v25.toml",
          "size": 8074,
          "sha512": "91554d735d35696791f0d5a82b0d1ce70221b45089e046a0a7ff5e303d2422d7fae7640544258fa6cebe12a74c289ef7eadb2038c863971e6a15a935be05ba97",
          "sha256": "f5eb60a5a64a0979d63411f57dc55787a49fac996b88de40eb287f18a3ee651c",
          "sha1": "465dea0eb774eb748816a013a618a0b253432af2",
          "md5": "a6d0b27951aef8f3280624aff6626769"
        }
      ]
    }
  ]
}
