architectury {
    common rootProject.subprojects.name.collect { it.toLowerCase() }.findAll { !it.contains("common") }
}

loom {
    accessWidenerPath = file("src/main/resources/${modId}.accesswidener")
}

dependencies {
    // Fabric Loader
    modCompileOnly libs.fabricloader.fabric
    
    // Multiloader Access Wideners
    if (libs.hasProperty("multiloaderaccesswideners") && libs.multiloaderaccesswideners.hasProperty("common")) {
        modCompileOnly(libs.multiloaderaccesswideners.common) { transitive = false }
    }

    // Mixin Extras
    compileOnly(annotationProcessor(libs.mixinextras.common.get()))
}
