{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.4-v6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.4-v6.toml",
          "url": "sharedcatalogs-1.21.4-v6.toml",
          "size": 9362,
          "sha512": "b7cca7ee802328df3e3759a83f1a8b88f86143ec7435413e60a0cdff588ce49d029b99c6de592d9cd51b11d29531b8267b77be137bcb28de195665ec6d5903fb",
          "sha256": "ba40b119bdd6aa67c75202d60050e3c0c78d8b3386ef17c66beef88565c5dda2",
          "sha1": "54f55a32b956875272b1186a829d9047bf5b959c",
          "md5": "99f678a865bfda7809a3f78577997955"
        }
      ]
    }
  ]
}
