{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.puzzleslib",
    "module": "puzzleslib-neoforge",
    "version": "26.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.10.jar",
          "url": "puzzleslib-neoforge-26.1.10.jar",
          "size": 1061097,
          "sha512": "37519741b18a7b88f36ed8b28749021229d06cc022ae5f2e5369ccfd106ce699a8a4bcac85499914c944a6dfbdf049b1b8b0b8d23132efb82d56c2f6daee4147",
          "sha256": "8963789d62ddb9415109e56852bf68a2411a6610de3d2e7591d428213aed548a",
          "sha1": "21585d62b7af45c7aeb67dc79590547f262f1d8f",
          "md5": "bcee5daf90c720cbc594c33224d282d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.10.jar",
          "url": "puzzleslib-neoforge-26.1.10.jar",
          "size": 1061097,
          "sha512": "37519741b18a7b88f36ed8b28749021229d06cc022ae5f2e5369ccfd106ce699a8a4bcac85499914c944a6dfbdf049b1b8b0b8d23132efb82d56c2f6daee4147",
          "sha256": "8963789d62ddb9415109e56852bf68a2411a6610de3d2e7591d428213aed548a",
          "sha1": "21585d62b7af45c7aeb67dc79590547f262f1d8f",
          "md5": "bcee5daf90c720cbc594c33224d282d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.10-sources.jar",
          "url": "puzzleslib-neoforge-26.1.10-sources.jar",
          "size": 535259,
          "sha512": "9223c00e3c3b8d09b2033c80faa454309e0e89f7fd606a331bc0efef7b356d712b9d0a9663e04e21f61ac297fc81234ae6cd3d6e473cfcd6906747924717a0d3",
          "sha256": "ec3cf007f05c2a5e65f0fc42353eebef0286d4f7d51d08367b70993d91f253f9",
          "sha1": "b1ee3c854e9ca6c9c682236c4b723e7e81a9728e",
          "md5": "858bf850f4cf5a7fef1e642c507f20fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.10-javadoc.jar",
          "url": "puzzleslib-neoforge-26.1.10-javadoc.jar",
          "size": 6923605,
          "sha512": "318a1b0d57ace32f3d421e608fb54ac4a1134c3437504af5caf5d075bd4553534451344a2bcf50e22212dffff4f6b1adf2fec3599ac8189f217940c406e84a4a",
          "sha256": "994b203c3e54ac80a62750fb6681019f7f9350d510f029cea81d35f4faa5353a",
          "sha1": "0d53a37addd18b11efa578238446b589bb904cf9",
          "md5": "e5c6a45257797d5b34b378f068dd0a17"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.10-accesstransformer.cfg",
          "url": "puzzleslib-neoforge-26.1.10-accesstransformer.cfg",
          "size": 99824,
          "sha512": "59fcaf2750d6d04a51d4e1dff9d9a4adcc6de44fa6609bdf9e138773c0db58aab0c9862fa2e2f0b94d1f605d3eb7a730d2439237c7faeb8a72af7c88a0ec4364",
          "sha256": "ddfa98260aa6320df732072ffdaa1774df671c4428f7c85bc6d7ca8251b188fa",
          "sha1": "3e324829b59d252ebe7c3d3879639003bb52e446",
          "md5": "99f3080d1075ffc62fb905a633b0d174"
        }
      ]
    }
  ]
}
