{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v3.toml",
          "url": "sharedcatalogs-1.21-v3.toml",
          "size": 7219,
          "sha512": "b1a0ec407c13182f2c541721f606fce0c4ccf2de1800b549af810851f42a45b62d93a1bfc1a438164a9efa9aa9dcee83c001d8f4bdd3ea211bd1ad8c58e81e13",
          "sha256": "5daf06c0651ac71c5d4a91fc690cc945c73bc34076ebc447af2651de559cc539",
          "sha1": "ddc189e49c2f8981aec50c89a1ab924c83da3b7b",
          "md5": "b722bccc1f78f23c93fc5167c87d4b22"
        }
      ]
    }
  ]
}
