{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v29.toml",
          "url": "sharedcatalogs-1.21-v29.toml",
          "size": 10200,
          "sha512": "2e0582351ace0e8c14134bcc355311e2e13bb38306214c299ca0ab3341e6a4f6ea889a1c1050c9d8a0c9c3c265159c52236ce75ca45585df75cd3bd6e6c212d2",
          "sha256": "6c7a3f30713cb11f01026b4865c46cdd39f95dbe2de4737a26e840e00fc8c6a9",
          "sha1": "165a884f7cab134bca667aa645cc1359592db276",
          "md5": "3c994fde752418da3db0858228199cbf"
        }
      ]
    }
  ]
}
