{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "26.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-26.2-SNAPSHOT.toml",
          "url": "sharedcatalogs-26.2-SNAPSHOT.toml",
          "size": 9670,
          "sha512": "fee37f951748052afda04fb195150e243ad3aff467fb27b4f451b21a3a00d863d95d7135b1394c2501d94689cb42fcdb6bb1cdcfe423deadc4c20287c2337878",
          "sha256": "6e05fdf6db9b0056ac23cce3b23b98d60626d532f105a712197ce52493496e59",
          "sha1": "7b0751f45fed95e6f241982dc38d24ffc792483e",
          "md5": "77eacd1e38c3e6927ce6e052ffe323ba"
        }
      ]
    }
  ]
}
