{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.4-v36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.4-v36.toml",
          "url": "sharedcatalogs-1.20.4-v36.toml",
          "size": 13325,
          "sha512": "0a564d17519a308b433b2789c265249a6e208e0ac2ce61a10b48c7708858e274ff4339cf45c96452b9cb9a455b151e39085ff72c626e230451a3414114857343",
          "sha256": "dace884985da7f689e25ae13b2e3c44eda1e4affc187d5e55a0bb749a3a9bda6",
          "sha1": "261eb8c966da6dd5c547c346db19fcc354b5118d",
          "md5": "a7ba527c1a4cf63fa47fb1e6888eb211"
        }
      ]
    }
  ]
}
