{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.22.jar",
          "url": "multiloader-convention-plugins-1.1.22.jar",
          "size": 1955009,
          "sha512": "73de30cb4c8c099ab01ead168ddbdf7f49aa16e0a4207f591b7084018620d621324f66bd8e68bc20b25bd5d53a4ced765238d83f0af0a69c7da21899d79aae3e",
          "sha256": "ab42a67b84245fd659037826aaf80c1acb35c59da82e5d0354a18a3b9394f4f4",
          "sha1": "ca8435441e5a2cf047054eeedf2c9ce3f1eb216c",
          "md5": "c140b0aa80cc3b638f92608ab58eb3f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.22.jar",
          "url": "multiloader-convention-plugins-1.1.22.jar",
          "size": 1955009,
          "sha512": "73de30cb4c8c099ab01ead168ddbdf7f49aa16e0a4207f591b7084018620d621324f66bd8e68bc20b25bd5d53a4ced765238d83f0af0a69c7da21899d79aae3e",
          "sha256": "ab42a67b84245fd659037826aaf80c1acb35c59da82e5d0354a18a3b9394f4f4",
          "sha1": "ca8435441e5a2cf047054eeedf2c9ce3f1eb216c",
          "md5": "c140b0aa80cc3b638f92608ab58eb3f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.22-sources.jar",
          "url": "multiloader-convention-plugins-1.1.22-sources.jar",
          "size": 868049,
          "sha512": "d4c9aa1e18cb326482862e36eeeee5d35cee8574f191302b7e8aa93c8ca90e78e437221e6ba9d1e85d8f825a7c22eee85b6f8e80a2757aee1e4a8aefbd6f68b7",
          "sha256": "6f5fd4dd267579e11ca9c408d42faca7a4d10d0755cd544168d98485a4fac7c8",
          "sha1": "bc493b46abb80f16fb7e6dc242fc9a58514c3563",
          "md5": "a636a78758755cf088a8344b97f65378"
        }
      ]
    }
  ]
}
