{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.8-v10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.8-v10.toml",
          "url": "sharedcatalogs-1.21.8-v10.toml",
          "size": 10823,
          "sha512": "5221829eea11173cb7d62b66cdb14932fb299ae021d908f9ddf8dd0318b3d6d88f550a32e77a4aa520226b21921810dc983aa2d0e8bbed3bd32963a22f0c246c",
          "sha256": "e80048b4c8c585483d8e72fca73b5c0d23f683f62d51be11fa3d3dbd17e1060c",
          "sha1": "5ec1ec9d8188162c96ca77413c88d8ca1f22c155",
          "md5": "fe39078d9f404ba2b6a75f5c4bbb12b9"
        }
      ]
    }
  ]
}
