{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.4-v37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.4-v37.toml",
          "url": "sharedcatalogs-1.20.4-v37.toml",
          "size": 13325,
          "sha512": "1002a19cbe69fa8f6d6b2542e1fec02b5b241bc8951e368d0256a65636e7e8747dbe8cf446b062b1e1dc36207799f742035636991049c1134d060e49719e139c",
          "sha256": "54355787843a7bc8c7169913f112793108d76ad9fc32641689f7c1eabf18928f",
          "sha1": "b52a46701811eabb06e72c2b99ea9d720cdc659d",
          "md5": "400258fb71e2f4fad411fe8645fd2b53"
        }
      ]
    }
  ]
}
