{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.6-v10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.6-v10.toml",
          "url": "sharedcatalogs-1.21.6-v10.toml",
          "size": 7456,
          "sha512": "b97dcce327f4ad72cbb50da8c22f74dccc28c93adf04d3237688aa12ed83284f92fa53958accaffa7bea6373c108b976e5aa873f87e28c03415c83a1547978e7",
          "sha256": "0d840b30c49762b384d2666347d3dc30d8a2aa96b6a0ed5df44652865b13c91b",
          "sha1": "f1375bcc502ffb7643e36d781f6d816a7c1d7ec1",
          "md5": "068318aa799dd4f24d78275a76412757"
        }
      ]
    }
  ]
}
