{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.18.2-v15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.18.2-v15.toml",
          "url": "sharedcatalogs-1.18.2-v15.toml",
          "size": 6628,
          "sha512": "b68d9b5facf0fd1cc58f6dd284fdc04976a9afe249f0bb79b4315c5f4f35baa8a8fc71d1f49e9b9411c297d3895daafa4fbaeafd3747fd79d75a09a4182b18fd",
          "sha256": "4b938f7c891aaba649d4526b50967b992cae5f74c805a1ae1a182068c5fe8b1d",
          "sha1": "c5f5b09cf742de97da96e3371f97df3b8ee7b24d",
          "md5": "9eb705844e6c1f1c5da71aabdb775a9a"
        }
      ]
    }
  ]
}
