{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.puzzleslib",
    "module": "puzzleslib-neoforge",
    "version": "26.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.11.jar",
          "url": "puzzleslib-neoforge-26.1.11.jar",
          "size": 1061226,
          "sha512": "ad89a120dda116b47979701179edad30641b3e9e8efc529c3b76136048de95a9d0fff5df86d208afc02a7125f2a63710922e823c5873082e8d26d857d56c5485",
          "sha256": "22305d89046cc7eb83a50de4bcd8370d2949c69454908c5365540b1e250aa492",
          "sha1": "0d1a71a7a60edfbd91b6c93f8a5f2400908ba041",
          "md5": "176bad5d21372269245ea3bd2ea237c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.11.jar",
          "url": "puzzleslib-neoforge-26.1.11.jar",
          "size": 1061226,
          "sha512": "ad89a120dda116b47979701179edad30641b3e9e8efc529c3b76136048de95a9d0fff5df86d208afc02a7125f2a63710922e823c5873082e8d26d857d56c5485",
          "sha256": "22305d89046cc7eb83a50de4bcd8370d2949c69454908c5365540b1e250aa492",
          "sha1": "0d1a71a7a60edfbd91b6c93f8a5f2400908ba041",
          "md5": "176bad5d21372269245ea3bd2ea237c1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.11-sources.jar",
          "url": "puzzleslib-neoforge-26.1.11-sources.jar",
          "size": 535423,
          "sha512": "d4c9010d652cfbc076847fe22eef67444d4090c300fd77d6564c45d530bd71f424c79a299d0171203fe52be325748125a25caf6023e840d4e32903448cb79457",
          "sha256": "874364abf06f08c3f74489522ea443f35598422ee0e2f2f82aa531e39df7d05d",
          "sha1": "5769757da370a504cb3dfc373d4b5ebc2778cc97",
          "md5": "1c2fab36b7fed68e83d8e4606ca2fec4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.11-javadoc.jar",
          "url": "puzzleslib-neoforge-26.1.11-javadoc.jar",
          "size": 6923512,
          "sha512": "e3348c6af4b786c190c84a11d8dc5e9b247d7e1dd62dadbf65a6345dab53a6d4fabe38caf79dc23ab9267fdec8b72e655839aa3ba19122ae96695d119c80b401",
          "sha256": "7797269400ee9e6635c37ac32f8b5c45f2b8d503bba331d24f22a59c57cd829c",
          "sha1": "13a0b8dd81e175f8bb5a67930d142f73ecb8ecc0",
          "md5": "35c0ca92dc3a0a87a9e6dec0680eadd8"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.11-accesstransformer.cfg",
          "url": "puzzleslib-neoforge-26.1.11-accesstransformer.cfg",
          "size": 99824,
          "sha512": "59fcaf2750d6d04a51d4e1dff9d9a4adcc6de44fa6609bdf9e138773c0db58aab0c9862fa2e2f0b94d1f605d3eb7a730d2439237c7faeb8a72af7c88a0ec4364",
          "sha256": "ddfa98260aa6320df732072ffdaa1774df671c4428f7c85bc6d7ca8251b188fa",
          "sha1": "3e324829b59d252ebe7c3d3879639003bb52e446",
          "md5": "99f3080d1075ffc62fb905a633b0d174"
        }
      ]
    }
  ]
}
