{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v19.toml",
          "url": "sharedcatalogs-1.21-v19.toml",
          "size": 9581,
          "sha512": "fa50d6443b781b31722587cd41c431e576f694f4fbc91085ba7d1188808ade758a533cf4130c5141b0e6fcdb57b27f541608135546cd4e5e6ce97b9bffa86ff6",
          "sha256": "0de6ba74e7e0802aad62298c042fd5f8e41061deaca4d0691dd3aa59b48dce3d",
          "sha1": "3185b4619d84a1855f419ffeaf5e11cf3a3d574f",
          "md5": "205ba34b43279516dbd1432180d9e953"
        }
      ]
    }
  ]
}
