{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.4-SNAPSHOT.toml",
          "url": "sharedcatalogs-1.20.4-SNAPSHOT.toml",
          "size": 13487,
          "sha512": "bee0ceb5cebc64ca703d998a7297ebfb086556244c989e6f530aff0ed9f27844c522c7defad575b293f10d143008ed55c2132d239daecf03043b5abe5fc97e10",
          "sha256": "87ccec478f5aff44b5570b69b25742b1450a02cb83131e62cd1e5a375abdc985",
          "sha1": "d1a8da6cdfd33113b090c0a89dfab9d03c737e0f",
          "md5": "43f3c382ed1acb75e13574ce6165dd9b"
        }
      ]
    }
  ]
}
