{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-26.3-SNAPSHOT.toml",
          "url": "sharedcatalogs-26.3-SNAPSHOT.toml",
          "size": 10079,
          "sha512": "cda3271bf791e6ddc537390940e36fecb4434a36251972fc99fb7af8d468b3b39f1f499871f4883502a9b6d718ad771f5daf529dfee2716fe397c675cfb8f1bb",
          "sha256": "d8dc3a6b2854ae5a838b58aea6c5540fba9bb0b8b0492b3907312c0246b0dd47",
          "sha1": "5a9c307b11d469d079f978efc961bfc80423b462",
          "md5": "969b167308eed742445619df4cbbb50b"
        }
      ]
    }
  ]
}
