{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "26.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-26.3-SNAPSHOT.toml",
          "url": "sharedcatalogs-26.3-SNAPSHOT.toml",
          "size": 8462,
          "sha512": "32029d4b8df1e47d8c16971984c2d804f9537590b58b03ee5c46214399016b834a46b000f1cd51f069a0d06ac19c776ce407ddc5f32c2250c13e4bc4e61bb871",
          "sha256": "b025115cb968102882641a609c03517f608b8d9c54251bac07fe0d4902695a8d",
          "sha1": "8fc72bef7936a86f7abb6e692aafbd644ef90e53",
          "md5": "0c46f0ea7b9c06be2f4844ff3575ea84"
        }
      ]
    }
  ]
}
