{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.1-v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v5.toml",
          "url": "sharedcatalogs-1.20.1-v5.toml",
          "size": 5801,
          "sha512": "e2d55c352b274c0d6b88f913443100a79f4b8f3bca76f4d9ccbd35b22330732fbf6343ec41d9d7f9dc24519a898e4da7b22dbcb759996220f7f06d7de839c1be",
          "sha256": "7176a69c13348978afbefcbc92371d089bbf288ed9849d0bf7fab6b0086c0a5b",
          "sha1": "7b03b079da0767ed18cfddfe0af50fdd079822c3",
          "md5": "aa8572c09befa9d5ba80234d63b78a53"
        }
      ]
    }
  ]
}
