{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.tooltipinsights",
    "module": "tooltipinsights-common",
    "version": "26.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-common",
          "version": {
            "requires": "26.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipinsights-common-26.3.1.jar",
          "url": "tooltipinsights-common-26.3.1.jar",
          "size": 79918,
          "sha512": "78df8dfaa1deda784da2641570a50088d873cfe8b5864ae642003576243a8bac137779cfe4b44eee8c8e0523fa8306f0798aaf4481eb0f3bf262729ef5202dc8",
          "sha256": "89f798485d06288b977861d3c8d21f25adf9622926406758ee1f9d8f6ab08e86",
          "sha1": "6ca0d7951f330590408465001c6465c15f1a380e",
          "md5": "d14e817b05ced9070d33fca44c86ff37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.1.jar",
          "url": "tooltipinsights-common-26.3.1.jar",
          "size": 79918,
          "sha512": "78df8dfaa1deda784da2641570a50088d873cfe8b5864ae642003576243a8bac137779cfe4b44eee8c8e0523fa8306f0798aaf4481eb0f3bf262729ef5202dc8",
          "sha256": "89f798485d06288b977861d3c8d21f25adf9622926406758ee1f9d8f6ab08e86",
          "sha1": "6ca0d7951f330590408465001c6465c15f1a380e",
          "md5": "d14e817b05ced9070d33fca44c86ff37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.1-sources.jar",
          "url": "tooltipinsights-common-26.3.1-sources.jar",
          "size": 46666,
          "sha512": "bab506c7829c595ffe6a8602f4957d0b5ba72767cd654e319e02e68ae9083890e36d34e31f6af1fc51f0e25d16b6ec0ededff37b9699dbf11cf4ab0cfa53044b",
          "sha256": "18a1c2e18fcb7a7d826c500705ab996cad58cc769b63ad69e3f85ab4f37607e4",
          "sha1": "ae1eba94c68143a8fabdc5d369cd4ec847bd0db5",
          "md5": "98d1912eecea958ed76fc68020bc6864"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.1-javadoc.jar",
          "url": "tooltipinsights-common-26.3.1-javadoc.jar",
          "size": 4254837,
          "sha512": "06c1c2d31948520741faae5243c6d7b5221ab6822292867cbaff5fbecc52a0ac85dcedd95655ff220be7d4112292b55e33e5dcb3ec0e1bf1f1fe90eff29c707b",
          "sha256": "4f1c8c46b66c006deb5bdfabca7b13a2154cec1229ae417637b6694a51a2a29b",
          "sha1": "759bf9f2f91c3c8b6830d9c88be3829df014c328",
          "md5": "e43439d7d2c5337ed09a5f848bda910b"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.1-accesstransformer.cfg",
          "url": "tooltipinsights-common-26.3.1-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
