{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.5-v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.5-v4.toml",
          "url": "sharedcatalogs-1.21.5-v4.toml",
          "size": 4686,
          "sha512": "2b9ae261213176febf14c9aa8ad86a3c3711a33c652467671b39c253c58d34b20f4a016ade0f828a5d52d6d3f9544b0190d7eab67d1031ce5b83c762a889873c",
          "sha256": "dced9a4677ee15edc74bce03666c6dbb0a614f829fa8edec336a44907a3cca1c",
          "sha1": "62bca31aa69be501b2cb284c1e6b227916ff6f06",
          "md5": "d4b8dc383ce2a75c488eda6302dd567e"
        }
      ]
    }
  ]
}
