{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.36.jar",
          "url": "multiloader-convention-plugins-1.1.36.jar",
          "size": 2419232,
          "sha512": "eda93933d4862b343db11d5c42578219de154304dd3805782c836db6f7dd960b804bd83e8c768e417c583cc7b3db6c124d8541650efdb779faef87e1972cc65d",
          "sha256": "b788b7cbfda1dc79b1abb215fbb4c6a98a72d4c2fc53aae9e61ff45cf7cb7442",
          "sha1": "64e5cf06b579e91bf9b5c09c4284dd161b6de7d0",
          "md5": "cb71473339f9717fa8649facf0f80e0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.147"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.36.jar",
          "url": "multiloader-convention-plugins-1.1.36.jar",
          "size": 2419232,
          "sha512": "eda93933d4862b343db11d5c42578219de154304dd3805782c836db6f7dd960b804bd83e8c768e417c583cc7b3db6c124d8541650efdb779faef87e1972cc65d",
          "sha256": "b788b7cbfda1dc79b1abb215fbb4c6a98a72d4c2fc53aae9e61ff45cf7cb7442",
          "sha1": "64e5cf06b579e91bf9b5c09c4284dd161b6de7d0",
          "md5": "cb71473339f9717fa8649facf0f80e0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.36-sources.jar",
          "url": "multiloader-convention-plugins-1.1.36-sources.jar",
          "size": 1175406,
          "sha512": "9c4420909fcf8a12e0099a5032e52f85ba0c9b11e9ad0300c8169390cd60350006ab0e4f4d84ae99d600a553441a708ec8a7b25e0ec0a75cbedbdb9ceebe5495",
          "sha256": "f14d2e337a053b095247f1c72ff395f7fbc40e2e0357d7fac81a61c9b1c277b2",
          "sha1": "edec7144acb3a0ff024178d47934a86c951f350a",
          "md5": "71a9d27a09a5661110dfdd8a59de716d"
        }
      ]
    }
  ]
}
