{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.3-v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.3-v4.toml",
          "url": "sharedcatalogs-1.21.3-v4.toml",
          "size": 6076,
          "sha512": "62e0df9a871db778b0cc6ee19422288ca43cb09e547ddf80299e2aa87b81fd87dc464e737b7dc2f0122b5c21811debee37ecc1e514c33f976c1e76d6bc6dd48a",
          "sha256": "7657340b236a83166f9bc03d06f0e16ab66098428276da5c98fc7e564fa4b5f8",
          "sha1": "2f76efba076ab209edba26156bfe626ba68ce539",
          "md5": "82a18f3e652866a9d8da9a9ede6fbc4e"
        }
      ]
    }
  ]
}
