{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.1-v8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-v8.toml",
          "url": "sharedcatalogs-1.20.1-v8.toml",
          "size": 6315,
          "sha512": "9806b4a6b703c6f06ccb7fc90018b049c92263f33889f73c2e92bde4aaa78094bb10535e9aa5c7de399134070c0eb65baec3c732cba9f355fc633af856cb9673",
          "sha256": "3d160f3b083839705a2d1be192a2a36de5de80f2ea54a776a23d9a2948927d25",
          "sha1": "074d4fccb93785d245b03deaf92a4725078d7700",
          "md5": "ba2d1dfc53e079098447a2b4ad80cefb"
        }
      ]
    }
  ]
}
