{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.3-v19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.3-v19.toml",
          "url": "sharedcatalogs-1.21.3-v19.toml",
          "size": 9699,
          "sha512": "78fb8102c1fe4b5351fb861691d1a99c34be1747cfb456bde0b3db95bb82bc2c5650236dec0b7b7727a60597b3efb248c3bf70e0720ed6bf97c0c9bfc1f4c58d",
          "sha256": "803711b0f9395c6976ea25edc38c9cbb2832d5d1ef40e3c6dbc6a4c0df69d800",
          "sha1": "2af1274dabc6a8e63c58111bcda0295062bd57d2",
          "md5": "6ba2d03979a037252c0766ce3227d482"
        }
      ]
    }
  ]
}
