air-hop=5
all-the-heads=35
arcane-lanterns=10
armor-quick-swap=20
armor-statues=25
armored-foes=25
azalea-growth-control=0
bag-of-holding=15
bartering-station=35
better-animations-collection=50
better-tridents=30
block-runner=20
bloomcraft=30
bundle-upgrade=30
climate-rivers=40
combat-nouveau=20
completionists-index=20
configured-defaults=0
convenient-effects=15
cut-through=35
death-finder=5
delete-worlds-to-trash=5
diagonal-fences=50
diagonal-walls=30
diagonal-windows=30
distinct-potions=15
dyed-flames=25
easy-anvils=50
easy-magic=50
easy-shulker-boxes=50
echo-chest=20
effect-insights=40
enchanting-infuser=60
enchantment-insights=40
enchantment-switch=15
ender-zoology=25
eternal-nether=50
falling-leaves-plus=55
fantastic-wings=35
fast-item-frames=35
forge-config-api-port=0
golden-age-combat=10
hang-glider=25
health-bars=40
held-item-tooltips=30
hopper-gadgetry=20
horse-expert=10
hovering-hotbar=10
illager-invasion=50
leave-my-bars-alone=25
leaves-be-gone=50
let-me-sleep=10
linked-chests=20
locked-in-slots=10
magnum-torch=35
metal-bundles=10
mindful-darkness=35
mob-lassos=15
mob-plaques=25
mutant-monsters=45
name-tag-upgrade=35
natural-waters=25
nether-chested=30
open-together=50
overflowing-bars=55
paper-doll=20
party-creepers=10
permanent-sponges=10
pick-up-notifier=70
pixelshot=10
portable-hole=5
puzzles-lib=0
reach-behind=20
resource-pack-overrides=0
respawning-animals=5
sea-life=35
sheep-variety=5
shroomcraft=40
skeleton-ai-fix=10
slot-cycler=15
sneaky-curses=5
spiky-spikes=15
stonecutting-upgrade=20
stoneworks=45
straw-statues=40
stylish-effects=35
sword-blocking-mechanics=5
tiny-skeletons=25
trading-post=40
universal-bone-meal=30
universal-enchants=20
vehicle-upgrade=40
vibrant-parrots=15
village-masquerade=15
visual-workbench=70
