{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v10.toml",
          "url": "sharedcatalogs-1.21-v10.toml",
          "size": 7470,
          "sha512": "9e604b02bac6639ff7b23cd3f7990ced521d339d91f76fa78738480eef91f35736dfe51426d4fc4907919b3fdd255d08a5e0743fea2c54cbb5abc34acfcf8369",
          "sha256": "644ced8bf0d0d90bccb53ec575c38fb1865c5b1c678cffd6e69700f79d5b3ca3",
          "sha1": "63a404fe71501e200d26b723335401aa2f333456",
          "md5": "cf873d3c4c6d5c8c536baa8f643f9d51"
        }
      ]
    }
  ]
}
