{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.statuemenus",
    "module": "statuemenus-common",
    "version": "26.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-common",
          "version": {
            "requires": "26.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "statuemenus-common-26.3.0.jar",
          "url": "statuemenus-common-26.3.0.jar",
          "size": 273241,
          "sha512": "d39dc3054dbb244c120d7e12b71ff4a111ab8a0adab803b88ec6addbf77c70b92688003f9427db62b0f25567b5de866bb67f79aa415704791b9f0b41f84973ac",
          "sha256": "4ad81de7a5d9961c00d77cc40b526d6cfaf142b585c0a47684403e5ef35652e7",
          "sha1": "3065fe5f2513e1c4a46281c96a8b0e300cfaf524",
          "md5": "f5caa306fd787b8fca92738a4ce55e04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "statuemenus-common-26.3.0.jar",
          "url": "statuemenus-common-26.3.0.jar",
          "size": 273241,
          "sha512": "d39dc3054dbb244c120d7e12b71ff4a111ab8a0adab803b88ec6addbf77c70b92688003f9427db62b0f25567b5de866bb67f79aa415704791b9f0b41f84973ac",
          "sha256": "4ad81de7a5d9961c00d77cc40b526d6cfaf142b585c0a47684403e5ef35652e7",
          "sha1": "3065fe5f2513e1c4a46281c96a8b0e300cfaf524",
          "md5": "f5caa306fd787b8fca92738a4ce55e04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "statuemenus-common-26.3.0-sources.jar",
          "url": "statuemenus-common-26.3.0-sources.jar",
          "size": 171034,
          "sha512": "f537dd78309078d4500bb7aa5fb08fb5a8225f4dd50df5a7838f1d8f6ce5b7ab74297fa0736ec81d788c803842a5c3d5bf79cc5229d4c40cfb6cc53f6b5a3f69",
          "sha256": "a2b4cbbf4d755fe798486495e4c562eb4324b9a12501591e18796fb80d1d8db2",
          "sha1": "f5c47303ccdd6c0118c4e4546d9035e363660ad2",
          "md5": "2c45c3a821c2f36c0cab7b30d17c40a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "statuemenus-common-26.3.0-javadoc.jar",
          "url": "statuemenus-common-26.3.0-javadoc.jar",
          "size": 4490786,
          "sha512": "3dbea925c08425c5100f0bcd049e2572455498a6d9377cd6573516ba5c5d61dfcbc155978019eeb961ab99347cbdc6b7684f1b96c9b7a9eeb0ebbc4146d8bed2",
          "sha256": "700cca5b1793f16987919535b9007590bdd2fe0244bba341ee95a7180e11e283",
          "sha1": "70d06ba86c9710012fff53b19561081cd754a68e",
          "md5": "ea38ab7d38cdc7616d648e83a5ff1d43"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "statuemenus-common-26.3.0-accesstransformer.cfg",
          "url": "statuemenus-common-26.3.0-accesstransformer.cfg",
          "size": 227,
          "sha512": "25656f2876fe18b38d80a08cc7b08c64710afb00e45d8ddc6562ec4a262daaeaceb8f6a9af40cdcc6d2c168b188a00f1aef58fbb613c0da4b9fb3733876e5463",
          "sha256": "e46f6167ccb4f5391253fc7e013f668e8ac86a90a15469ae64d6f0f73a34864a",
          "sha1": "4b1139dc5520d4aa1cceeac340a152704c319ad4",
          "md5": "11eb011e01d508d2787287bacda3e46a"
        }
      ]
    }
  ]
}
