{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.25.jar",
          "url": "multiloader-convention-plugins-1.1.25.jar",
          "size": 1955255,
          "sha512": "9a9027e6ce81dd27daef61cb1d890f17078a75082358170a1ad9964bb40305095d1d33cec753afd71ad026e32e1d60d62b050a376116ea870029188da573491b",
          "sha256": "0dcf9d4946e1e39fb0d503659a6505977fa442f1bbf386bad0185a74c04d020c",
          "sha1": "c96b7a17b9794338081ed47e4617b83817031bda",
          "md5": "f7177794c153e65f88022d2736606818"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.25.jar",
          "url": "multiloader-convention-plugins-1.1.25.jar",
          "size": 1955255,
          "sha512": "9a9027e6ce81dd27daef61cb1d890f17078a75082358170a1ad9964bb40305095d1d33cec753afd71ad026e32e1d60d62b050a376116ea870029188da573491b",
          "sha256": "0dcf9d4946e1e39fb0d503659a6505977fa442f1bbf386bad0185a74c04d020c",
          "sha1": "c96b7a17b9794338081ed47e4617b83817031bda",
          "md5": "f7177794c153e65f88022d2736606818"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.25-sources.jar",
          "url": "multiloader-convention-plugins-1.1.25-sources.jar",
          "size": 868172,
          "sha512": "5992af9f75fac7d8867389263b40f5cbbca7721a4e3e26837b6798b179de331230336f05bfbd00a8ab136a72eca19a72a3590e91589a01b1a726e696a6f8c308",
          "sha256": "1569803bc9c2f08f0a85336678ef56aac759fdb5193150927cef9785090dd95f",
          "sha1": "9a8e60d658a46c7bfebd694c466ebbe22b7b2d93",
          "md5": "28dd1dbd74f3a6e4a0deff5e0cccfaa9"
        }
      ]
    }
  ]
}
