{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21.1-v4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21.1-v4.toml",
          "url": "sharedcatalogs-1.21.1-v4.toml",
          "size": 10730,
          "sha512": "94b9af24e1431d54e50772d17156db66835bbf019756e9d04d42fd0d778fd2a189eedd8d8ce9834a7b089a4cbf1f6f9f5384c06b7d4008f8f872b032dbfcc2e8",
          "sha256": "4a35d72d59e7ab5a3c147a40ed1eb847630182139f9e33b64a8f83730af55305",
          "sha1": "dabbf1660465168422fef7282df5ce68a6fc6b91",
          "md5": "7484ab68db41fa3e8de4b8fec3fa1b5e"
        }
      ]
    }
  ]
}
