{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.tooltipinsights",
    "module": "tooltipinsights-common",
    "version": "26.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-common",
          "version": {
            "requires": "26.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipinsights-common-26.3.2.jar",
          "url": "tooltipinsights-common-26.3.2.jar",
          "size": 80023,
          "sha512": "15de21e5f3af3cf090fea8dde358a8f7c9c04b4c4ae46133bd8cb4aaaa0e7ae16785be17b62a74f2a0f0320e665753dd6f93a1a04646943a7bcf11782e13d1f0",
          "sha256": "9bc9086e035308b8a35485cb443c44244e49c50bd454a06cd7b270e1d17521dd",
          "sha1": "32ea923b96e3b1846820e64d130d66071c0a911c",
          "md5": "4aaa81587c4a9a81c98e65a397952072"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.2.jar",
          "url": "tooltipinsights-common-26.3.2.jar",
          "size": 80023,
          "sha512": "15de21e5f3af3cf090fea8dde358a8f7c9c04b4c4ae46133bd8cb4aaaa0e7ae16785be17b62a74f2a0f0320e665753dd6f93a1a04646943a7bcf11782e13d1f0",
          "sha256": "9bc9086e035308b8a35485cb443c44244e49c50bd454a06cd7b270e1d17521dd",
          "sha1": "32ea923b96e3b1846820e64d130d66071c0a911c",
          "md5": "4aaa81587c4a9a81c98e65a397952072"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.2-sources.jar",
          "url": "tooltipinsights-common-26.3.2-sources.jar",
          "size": 46726,
          "sha512": "71b37d7a9939fd430742da340c4e37f8eec433bed7421fe2e42434215a974cf082508e887bf8b5bacc00958b7e3127ebc9f5052062f6ace97ac04ede26277aad",
          "sha256": "348e33a1aa0063b7776b60bfb8884028df16ddabfef5e7260c558b6ed6e8d60a",
          "sha1": "645df4448e234aa7f475413b26534397d2291681",
          "md5": "f1296ad28de596acfbd14ca2cce83c09"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.2-javadoc.jar",
          "url": "tooltipinsights-common-26.3.2-javadoc.jar",
          "size": 4254875,
          "sha512": "dd96795f0c45196f91655590ff9800a8d27f37800ec1def99635e4350aac2fcc6df02c3c9cae28de351c57e5781f77ff9e00a0f6b6bdfee693d2d3d21c118913",
          "sha256": "1a25d3e90208ef2bd1a6f8275412f43c4f6145b3b09105f473525ac591a568f8",
          "sha1": "94e8fdb2b2342dabbc9accacbede9a67267b803c",
          "md5": "aad0152b9fa076cb7a3420bc2fe9df82"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "tooltipinsights-common-26.3.2-accesstransformer.cfg",
          "url": "tooltipinsights-common-26.3.2-accesstransformer.cfg",
          "size": 0,
          "sha512": "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e",
          "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
          "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
          "md5": "d41d8cd98f00b204e9800998ecf8427e"
        }
      ]
    }
  ]
}
