{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-conventions",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-conventions-1.0-SNAPSHOT.jar",
          "url": "multiloader-conventions-1.0-SNAPSHOT.jar",
          "size": 1028010,
          "sha512": "924c14fc589d3e954b6d97b413e18e13dcca88e5f6e2d2ec2a613ed25f7d1079188a557fdb6275b1b6f9d5085d86fe2fc2a2c4369cb8e9b10e7943885d42f41b",
          "sha256": "ecb98bd278c79423320e709edcdad30ada545cfb4270dc903143b271b5bda005",
          "sha1": "25dc95087150c75bcd9340574ee671e2933d366e",
          "md5": "ccf21b16afbe33553b4e036d7a4cb11c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury.loom",
          "module": "dev.architectury.loom.gradle.plugin",
          "version": {
            "requires": "1.13-SNAPSHOT"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-conventions-1.0-SNAPSHOT.jar",
          "url": "multiloader-conventions-1.0-SNAPSHOT.jar",
          "size": 1028010,
          "sha512": "924c14fc589d3e954b6d97b413e18e13dcca88e5f6e2d2ec2a613ed25f7d1079188a557fdb6275b1b6f9d5085d86fe2fc2a2c4369cb8e9b10e7943885d42f41b",
          "sha256": "ecb98bd278c79423320e709edcdad30ada545cfb4270dc903143b271b5bda005",
          "sha1": "25dc95087150c75bcd9340574ee671e2933d366e",
          "md5": "ccf21b16afbe33553b4e036d7a4cb11c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-conventions-1.0-SNAPSHOT-sources.jar",
          "url": "multiloader-conventions-1.0-SNAPSHOT-sources.jar",
          "size": 311433,
          "sha512": "162494506c624d8de505e320c06167ee6feaba3ee3ca6ffc1c8879d4bd5d5fcd9893df362f3e1e5755a8a5f4da7024ce3008b0b7ea2b186c762a4c5507c60521",
          "sha256": "ed727cf4cb6ec38b6dc16e2402ea75e2f179a22f9eabdc1d04183a424b35e02f",
          "sha1": "48adc2e7751def973244f35ebff0d8a02715267c",
          "md5": "9dd7c909c2a404ac3582e2190862210c"
        }
      ]
    }
  ]
}
