{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.19.2-v5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.19.2-v5.toml",
          "url": "sharedcatalogs-1.19.2-v5.toml",
          "size": 5735,
          "sha512": "7803353976e9baf3949b359d97f25bd82a751a04f7a0cb0e337a6f21f3418a02118ee1a1717de511ed0ec9bccf738eb266f738cb63453a823c786682d36c4deb",
          "sha256": "7422735e3161b5dec6d788b42e7143ee9b23bfbd138da755539b81f44637c4a8",
          "sha1": "17f5e00b156ff7c5089e86707dbbb75faadd9c6a",
          "md5": "73f47dc4eca38ea7a5995f9f25cb12da"
        }
      ]
    }
  ]
}
