{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloaderaccesswideners",
    "module": "multiloaderaccesswideners-common",
    "version": "26.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "multiloaderaccesswideners-common-26.1.1.jar",
          "url": "multiloaderaccesswideners-common-26.1.1.jar",
          "size": 16529,
          "sha512": "59e2b45082249472c040cfd42b7c5606fe33f6a3465985cd5181ccdc6101a4941c639a4f0d650d5d351319155460e005cdec14c7aba3c258c5b53203c84702b8",
          "sha256": "0f558b728db474136514890514142d0b927f37153902e67832c2b47968019c30",
          "sha1": "8cd878682f00b1dc574b60bdb249e94159f18fa4",
          "md5": "2d0b39a6b9d16aea8d3ed67586542be2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloaderaccesswideners-common-26.1.1.jar",
          "url": "multiloaderaccesswideners-common-26.1.1.jar",
          "size": 16529,
          "sha512": "59e2b45082249472c040cfd42b7c5606fe33f6a3465985cd5181ccdc6101a4941c639a4f0d650d5d351319155460e005cdec14c7aba3c258c5b53203c84702b8",
          "sha256": "0f558b728db474136514890514142d0b927f37153902e67832c2b47968019c30",
          "sha1": "8cd878682f00b1dc574b60bdb249e94159f18fa4",
          "md5": "2d0b39a6b9d16aea8d3ed67586542be2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloaderaccesswideners-common-26.1.1-sources.jar",
          "url": "multiloaderaccesswideners-common-26.1.1-sources.jar",
          "size": 16499,
          "sha512": "e329629266689d6870d166b65e423367ec9a1e858fc8638d59768b1831924777407ee8d6fbdcc6980ad269a111641e4092ab050012ad2ab11c14dc6bb514e9fc",
          "sha256": "d5d63ca99208527ae2b8f83dad20541eca97afa1385a0d386711108df94a709c",
          "sha1": "8c20b8680f2fc72e92e82700463ea0cb00b2bb3b",
          "md5": "5bef1b24ef1dd956a74df67ad51fcc0e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloaderaccesswideners-common-26.1.1-javadoc.jar",
          "url": "multiloaderaccesswideners-common-26.1.1-javadoc.jar",
          "size": 6894,
          "sha512": "8ac773d960f001a6a1ff425f5e3edd5e734e9333f8f70b22b7e08cb480a014e7a8262e979a77113d5cebdc4bfa6f6af21176a4fc1d43a85cac413dc7b8ac6f87",
          "sha256": "158c5ebcffc0116622f7110a06763a2afd552876fc093a319355bb0eb21b9e41",
          "sha1": "b569e112d662a7190fb00e1587c2538f15dbf1af",
          "md5": "629ca2b6e5a3baf2e63e8f077dd17fe6"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "multiloaderaccesswideners-common-26.1.1-accesstransformer.cfg",
          "url": "multiloaderaccesswideners-common-26.1.1-accesstransformer.cfg",
          "size": 26268,
          "sha512": "6376a55c47a1312f2fc1a7bbd3709fbdc7aa0d248797cf3ee0f92c619a48021b56642f39b0b24799a20bcd58874e5b5446e779b35a6f72ed4fc6707b9c31529f",
          "sha256": "a32e079c0e2488e784e1cc1b0f5d5b292d01efeb02aeda4fd185cf60ea8069b5",
          "sha1": "65200325b2138804df3808d794519f2ae4a80e41",
          "md5": "3c800a995a306acb987aa8465b1cbb70"
        }
      ]
    }
  ]
}
