{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.21-v6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.21-v6.toml",
          "url": "sharedcatalogs-1.21-v6.toml",
          "size": 7482,
          "sha512": "440d34f2ceaf684c933d36abe67f9525a162820b9f6f330ffdf834346403e86596aa4b3ce0f6d6a2519181dca95176fc8c5b33d37619a4c2e0f035ba5d07738f",
          "sha256": "7d74d08cc838853178fc0bad7d914a28cd8d319eb1c8d33a408861e9ae583986",
          "sha1": "ee59f01bbcb1207cf7394982f90e5f94bedc3a83",
          "md5": "1e2dd9064474222d5f1ad5e2df6b39f9"
        }
      ]
    }
  ]
}
