{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs",
    "version": "1.20.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-1.20.1-SNAPSHOT.toml",
          "url": "sharedcatalogs-1.20.1-SNAPSHOT.toml",
          "size": 10717,
          "sha512": "f39d438e4907886fad6c47e1a93d84018b38fc6d544505e9e16eccaac2f53cf99518dde15d2574e4158c73f1e6d004b5f752f35e0a0d3b0a39011d5c4c0d9645",
          "sha256": "936bc03d6f29f8a52c79423714bb8a8a85d16644e7ac394923f4e00cf51e4862",
          "sha1": "cfb94dff07baac2044427ce2c01b35fb949b4256",
          "md5": "0baea6193e1fac077c8ba10d7e447b7f"
        }
      ]
    }
  ]
}
