{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.tooltipinsights",
    "module": "tooltipinsights-fabric",
    "version": "26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.152.1+26.1.2"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "26.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipinsights-fabric-26.1.2.jar",
          "url": "tooltipinsights-fabric-26.1.2.jar",
          "size": 84305,
          "sha512": "fb7768fd4c4ab334bb5d1c209d5928554dd27d48f8a2bb7145d80cedab0a135aeb873a37aa06f3db0f326edd476a784913b91ff8aed0c1f68d69a159f8303495",
          "sha256": "403df24972e9e470c33e300030c0e35c30b6bcb5854436eeabea928e6d071669",
          "sha1": "54bfe7ec5a2721d80d837de92c63a53b6d8dd3df",
          "md5": "53ff67d8cbcfb38a082e7222c09f7901"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.152.1+26.1.2"
          }
        },
        {
          "group": "fuzs.puzzleslib",
          "module": "puzzleslib-fabric",
          "version": {
            "requires": "26.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "tooltipinsights-fabric-26.1.2.jar",
          "url": "tooltipinsights-fabric-26.1.2.jar",
          "size": 84305,
          "sha512": "fb7768fd4c4ab334bb5d1c209d5928554dd27d48f8a2bb7145d80cedab0a135aeb873a37aa06f3db0f326edd476a784913b91ff8aed0c1f68d69a159f8303495",
          "sha256": "403df24972e9e470c33e300030c0e35c30b6bcb5854436eeabea928e6d071669",
          "sha1": "54bfe7ec5a2721d80d837de92c63a53b6d8dd3df",
          "md5": "53ff67d8cbcfb38a082e7222c09f7901"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-fabric-26.1.2-sources.jar",
          "url": "tooltipinsights-fabric-26.1.2-sources.jar",
          "size": 48255,
          "sha512": "5d54547043672e911ea5e5520e781bc9e6f21c53efa963f5a0200387f56c5edd99a1df80220abe77977d142b5dce4b6d64e4097662cd8b84f0beedb12303b07e",
          "sha256": "21faf9922560f0e60126372695898a90ac3eb9e7e5cd9e28e6ed79fbcdb867f0",
          "sha1": "1a249228b0d2c6b7aa9a61a2c3d9e66082cd0627",
          "md5": "f0768edb409f5f0e0cade936fd0b3783"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tooltipinsights-fabric-26.1.2-javadoc.jar",
          "url": "tooltipinsights-fabric-26.1.2-javadoc.jar",
          "size": 4267768,
          "sha512": "679b75804bb9a1ce28ff248d7b029a1a78a74777d4fac25d58af44fee79bd1d088613e8838bb6be8c54d94e1d6d6f0bb57278b786801b103a98a08c3daf7d408",
          "sha256": "7a8822125f6ce0841505bc2813468ed067cc1f0a1827ada68663aec39f188aee",
          "sha1": "242dfbc76dfa48b70fe1938b981f384b38d65920",
          "md5": "9f76d31e07235977cee7c210f30f9e61"
        }
      ]
    }
  ]
}
