{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.29.jar",
          "url": "multiloader-convention-plugins-1.1.29.jar",
          "size": 1972609,
          "sha512": "73e26c439186451308706b79c054ddd5851dd8880c43e79330fe4a7088a769bc868e124c004e8612cb712e93674894854fa6d923d115838994be5cd9a2e2cde7",
          "sha256": "8cf711a8586871bc526189a2068a3061a0fa2ea7bb664c432a0b25bee7ee8707",
          "sha1": "dd4515002a6b092d67e5cfa179bd295e34c3fde9",
          "md5": "46176c8527f8008ee99bb9e027791c91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.29.jar",
          "url": "multiloader-convention-plugins-1.1.29.jar",
          "size": 1972609,
          "sha512": "73e26c439186451308706b79c054ddd5851dd8880c43e79330fe4a7088a769bc868e124c004e8612cb712e93674894854fa6d923d115838994be5cd9a2e2cde7",
          "sha256": "8cf711a8586871bc526189a2068a3061a0fa2ea7bb664c432a0b25bee7ee8707",
          "sha1": "dd4515002a6b092d67e5cfa179bd295e34c3fde9",
          "md5": "46176c8527f8008ee99bb9e027791c91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.29-sources.jar",
          "url": "multiloader-convention-plugins-1.1.29-sources.jar",
          "size": 870808,
          "sha512": "98519360b8961cb39676acecb338aa52c06475edcb11f14d903a1350e90d9a5277bf042cc4126f7145d1607806e20f78fcfef0aac9434501f5aafd961d4ece1a",
          "sha256": "8fae23950d45246eca9a3585b204e03fc33cc8679b7af900ba81ca587f274021",
          "sha1": "75bf1e92ed21bddb8bfa4e358029f1df5fa80948",
          "md5": "489b87ccd1ecf9301e4fa1f5e18bc56a"
        }
      ]
    }
  ]
}
