{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.sharedcatalogs",
    "module": "sharedcatalogs-libraries",
    "version": "1.21.10-v7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "sharedcatalogs-libraries-1.21.10-v7.toml",
          "url": "sharedcatalogs-libraries-1.21.10-v7.toml",
          "size": 10673,
          "sha512": "fdaceab83e91ed9d33b1f5bcac74bc66a0e2390656b2661a658dc9381d137b6caf9a5867f006f95afd29d69cf3046f16887d2bea90c9e1d34fcd90b88d490d56",
          "sha256": "484223283c717f90ed114cb4f1be5ad33c58c65c625c62ff90db48e54711ed31",
          "sha1": "c3fea0ce73bcae20511802d67c9f601f8e8eb5cc",
          "md5": "812bbe1366e41b8494f81138fa0781f8"
        }
      ]
    }
  ]
}
