{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.puzzleslib",
    "module": "puzzleslib-neoforge",
    "version": "26.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.14.jar",
          "url": "puzzleslib-neoforge-26.1.14.jar",
          "size": 1064785,
          "sha512": "feb07101048f1b3c83538f475d9ed6e1215b40d70a24b0d1bd63dd11d32fc5f4ca50d109ab110b895037310dde805ab319390da7dcbe1c1c314e763ec86d02ce",
          "sha256": "3be2424bea293ce525fb6f75719f1cfd3c7102bb829000d7bcc4bfe9a320fd5a",
          "sha1": "920a89bee921d3b8e36b995e575095a65ae09f6c",
          "md5": "303129fd30f0debc6897293a92ee7173"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.14.jar",
          "url": "puzzleslib-neoforge-26.1.14.jar",
          "size": 1064785,
          "sha512": "feb07101048f1b3c83538f475d9ed6e1215b40d70a24b0d1bd63dd11d32fc5f4ca50d109ab110b895037310dde805ab319390da7dcbe1c1c314e763ec86d02ce",
          "sha256": "3be2424bea293ce525fb6f75719f1cfd3c7102bb829000d7bcc4bfe9a320fd5a",
          "sha1": "920a89bee921d3b8e36b995e575095a65ae09f6c",
          "md5": "303129fd30f0debc6897293a92ee7173"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.14-sources.jar",
          "url": "puzzleslib-neoforge-26.1.14-sources.jar",
          "size": 536564,
          "sha512": "58f09ddaeafbeaa4c005d247b099b745a74e5d945b5ce2051f4e501be7cc524ff1a6de7691964b3a0943cc3091d7aa8f5e34c16558258b57733f4af8996b9330",
          "sha256": "dcc49cdfc93f977f8f9741b6ecc464b75bb81962108fef876a5f76469378557f",
          "sha1": "817a794801091c69012f91de5ada4ec7afc74e96",
          "md5": "74c2a9ba65837a77ccdbef34cabb97fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.14-javadoc.jar",
          "url": "puzzleslib-neoforge-26.1.14-javadoc.jar",
          "size": 6924680,
          "sha512": "a763321c49d3c83655de417abd744b1da95804135e318f160139fb262fb811101da73a351d2182f30ebd1572b58c8e89cdaaa77966ac085a5ddd59de71a51858",
          "sha256": "7f11d803fa476dc982405b14b887fbec7bc226055180b005b847f33c08385d29",
          "sha1": "0d07154e1a90017523877acf02bbb6e63db50548",
          "md5": "3a777a5ab45e58cdde037c7a1b47a3a6"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "puzzleslib-neoforge-26.1.14-accesstransformer.cfg",
          "url": "puzzleslib-neoforge-26.1.14-accesstransformer.cfg",
          "size": 100009,
          "sha512": "ec01f0c67065ee66f61c0f9f275f56081963f9bae5a79bde14b5b4889f3daf6c9e5c780d3b87dad9cac25ca8baec17f7da2699595513f104c93918d55c922a0d",
          "sha256": "2714ad8a7edfdc62ac716adc500de8078234ae64c373e2f36d181d2de825ec85",
          "sha1": "9fd381ca7cee66deb2a2368c2203ddaaa283e170",
          "md5": "51c35fd70971c8759ebaa064ea2a4b66"
        }
      ]
    }
  ]
}
