{
  "formatVersion": "1.1",
  "component": {
    "group": "fuzs.multiloader",
    "module": "multiloader-convention-plugins",
    "version": "1.1.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.26.jar",
          "url": "multiloader-convention-plugins-1.1.26.jar",
          "size": 1955767,
          "sha512": "bdb63ed27fd48246df58bfe3e44fa7b5128f5fc254b00814e2e4f6237b61078ea2052498c8430f687ab32959a9d0cc06026d93e9d68b017eba73ad5d144bea0a",
          "sha256": "c8f4cc958b44dd4ecfdcdffc66902ff5ffbc037a55f1da35d4a1b2e14f558a03",
          "sha1": "70e765bcd605b2e361165e6f1ecb237c5be78287",
          "md5": "17391a9831fe4e19a9564dabe9606d67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.gradle.toolchains.foojay-resolver-convention",
          "module": "org.gradle.toolchains.foojay-resolver-convention.gradle.plugin",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.akuleshov7",
          "module": "ktoml-core",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom",
          "module": "net.fabricmc.fabric-loom.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.fabricmc.fabric-loom-remap",
          "module": "net.fabricmc.fabric-loom-remap.gradle.plugin",
          "version": {
            "requires": "1.16-SNAPSHOT"
          }
        },
        {
          "group": "net.neoforged.moddev",
          "module": "net.neoforged.moddev.gradle.plugin",
          "version": {
            "requires": "2.0.141"
          }
        },
        {
          "group": "me.modmuss50.mod-publish-plugin",
          "module": "me.modmuss50.mod-publish-plugin.gradle.plugin",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "com.diffplug.spotless.gradle.plugin",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.26.jar",
          "url": "multiloader-convention-plugins-1.1.26.jar",
          "size": 1955767,
          "sha512": "bdb63ed27fd48246df58bfe3e44fa7b5128f5fc254b00814e2e4f6237b61078ea2052498c8430f687ab32959a9d0cc06026d93e9d68b017eba73ad5d144bea0a",
          "sha256": "c8f4cc958b44dd4ecfdcdffc66902ff5ffbc037a55f1da35d4a1b2e14f558a03",
          "sha1": "70e765bcd605b2e361165e6f1ecb237c5be78287",
          "md5": "17391a9831fe4e19a9564dabe9606d67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "multiloader-convention-plugins-1.1.26-sources.jar",
          "url": "multiloader-convention-plugins-1.1.26-sources.jar",
          "size": 868408,
          "sha512": "9a5f6cfb8fc941dab022b70d0b1fb13aface7ee4d6af1e9abd881529a49d2881fe7593d5eeb0e140585c1c512fa9f9b125a8445c1c5b639ea27d5d0e7a5cdd42",
          "sha256": "56363c9315fc552dfd03887127b3149035151242c6bf2826da1da35ccf0f861c",
          "sha1": "a04f7e53e5810d31d793b4e559273c801525441b",
          "md5": "c41ca359fd26f9747206ac727237c0f2"
        }
      ]
    }
  ]
}
